// Nelson Alejadro Cosme Diaz 10142016
// Calculadora
public class calculadora extends javax.swing.JFrame {

    /**
     * Creates new form calculadora
     */
    public calculadora() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        textooperacion1 = new javax.swing.JLabel();
        textoresultado1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        textooperacion = new javax.swing.JLabel();
        textoresultado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        textooperacion1.setBackground(new java.awt.Color(255, 255, 255));
        textooperacion1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        textooperacion1.setForeground(new java.awt.Color(0, 0, 51));
        textooperacion1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textooperacion1.setText("5 x 10 +20");

        textoresultado1.setBackground(new java.awt.Color(153, 255, 255));
        textoresultado1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        textoresultado1.setForeground(new java.awt.Color(0, 0, 51));
        textoresultado1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textoresultado1.setText("31231231");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoresultado1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textooperacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(textooperacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoresultado1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        jFrame1.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 110));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton21.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton21.setForeground(new java.awt.Color(0, 0, 51));
        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton21.setText("÷");
        jButton21.setFocusPainted(false);
        jButton21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton21.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 50, 50));

        jButton22.setFont(new java.awt.Font("Century Gothic", 1, 28)); // NOI18N
        jButton22.setForeground(new java.awt.Color(0, 0, 51));
        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton22.setText("-");
        jButton22.setFocusPainted(false);
        jButton22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton22.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jPanel5.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 50, 50));

        jButton23.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton23.setForeground(new java.awt.Color(0, 0, 51));
        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton23.setText("%");
        jButton23.setFocusPainted(false);
        jButton23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton23.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 50, 50));

        jButton24.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton24.setForeground(new java.awt.Color(0, 0, 51));
        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton24.setText("^");
        jButton24.setFocusPainted(false);
        jButton24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton24.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 50, 50));

        jButton25.setBackground(new java.awt.Color(255, 255, 255));
        jButton25.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton25.setForeground(new java.awt.Color(0, 0, 51));
        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm) (1).png"))); // NOI18N
        jButton25.setText("Result");
        jButton25.setFocusPainted(false);
        jButton25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton25.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 120, 50));

        jButton26.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton26.setForeground(new java.awt.Color(0, 0, 51));
        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton26.setText("7");
        jButton26.setFocusPainted(false);
        jButton26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton26.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jPanel5.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, 50));

        jButton27.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton27.setForeground(new java.awt.Color(0, 0, 51));
        jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton27.setText("8");
        jButton27.setFocusPainted(false);
        jButton27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton27.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jPanel5.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 50, 50));

        jButton28.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton28.setForeground(new java.awt.Color(0, 0, 51));
        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton28.setText("9");
        jButton28.setFocusPainted(false);
        jButton28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton28.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jPanel5.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 50, 50));

        jButton29.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton29.setForeground(new java.awt.Color(0, 0, 51));
        jButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton29.setText("X");
        jButton29.setFocusPainted(false);
        jButton29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton29.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jPanel5.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 50, 50));

        jButton30.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButton30.setForeground(new java.awt.Color(0, 0, 51));
        jButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton30.setText("+");
        jButton30.setFocusPainted(false);
        jButton30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton30.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jPanel5.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 50, 50));

        jButton31.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton31.setForeground(new java.awt.Color(0, 0, 51));
        jButton31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton31.setText("6");
        jButton31.setFocusPainted(false);
        jButton31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton31.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jPanel5.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 50, 50));

        jButton32.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton32.setForeground(new java.awt.Color(0, 0, 51));
        jButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton32.setText("5");
        jButton32.setFocusPainted(false);
        jButton32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton32.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jPanel5.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 50, 50));

        jButton33.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton33.setForeground(new java.awt.Color(0, 0, 51));
        jButton33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton33.setText("4");
        jButton33.setFocusPainted(false);
        jButton33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton33.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jPanel5.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 50, 50));

        jButton34.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton34.setForeground(new java.awt.Color(0, 0, 51));
        jButton34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton34.setText(".");
        jButton34.setFocusPainted(false);
        jButton34.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton34.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jPanel5.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 50, 50));

        jButton35.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton35.setForeground(new java.awt.Color(0, 0, 51));
        jButton35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton35.setText("2");
        jButton35.setFocusPainted(false);
        jButton35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton35.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jPanel5.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 50, 50));

        jButton36.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton36.setForeground(new java.awt.Color(0, 0, 51));
        jButton36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton36.setText("3");
        jButton36.setFocusPainted(false);
        jButton36.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton36.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jPanel5.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 50, 50));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 290, 50));

        jButton37.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton37.setForeground(new java.awt.Color(0, 0, 51));
        jButton37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton37.setText("C");
        jButton37.setFocusPainted(false);
        jButton37.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton37.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jPanel5.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        jButton38.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton38.setForeground(new java.awt.Color(0, 0, 51));
        jButton38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton38.setText("1");
        jButton38.setFocusPainted(false);
        jButton38.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton38.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jPanel5.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 50, 50));

        jButton39.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton39.setForeground(new java.awt.Color(0, 0, 51));
        jButton39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton39.setText("0");
        jButton39.setFocusPainted(false);
        jButton39.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton39.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jPanel5.add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 50, 50));

        jFrame1.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 290, 320));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        textooperacion.setBackground(new java.awt.Color(255, 255, 255));
        textooperacion.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        textooperacion.setForeground(new java.awt.Color(0, 0, 51));
        textooperacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textooperacion.setText("5 x 10 +20");

        textoresultado.setBackground(new java.awt.Color(153, 255, 255));
        textoresultado.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        textoresultado.setForeground(new java.awt.Color(0, 0, 51));
        textoresultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textoresultado.setText("31231231");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textooperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(textooperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoresultado, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 110));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 51));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton2.setText("÷");
        jButton2.setFocusPainted(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 50, 50));

        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 28)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 51));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton3.setText("-");
        jButton3.setFocusPainted(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 50, 50));

        jButton4.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 51));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton4.setText("%");
        jButton4.setFocusPainted(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 50, 50));

        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 51));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton5.setText("^");
        jButton5.setFocusPainted(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 50, 50));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 51));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm) (1).png"))); // NOI18N
        jButton6.setText("Result");
        jButton6.setFocusPainted(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 120, 50));

        jButton7.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 51));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton7.setText("7");
        jButton7.setFocusPainted(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, 50));

        jButton8.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 51));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton8.setText("8");
        jButton8.setFocusPainted(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 50, 50));

        jButton9.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 0, 51));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton9.setText("9");
        jButton9.setFocusPainted(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 50, 50));

        jButton10.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 0, 51));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton10.setText("X");
        jButton10.setFocusPainted(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 50, 50));

        jButton11.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 0, 51));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton11.setText("+");
        jButton11.setFocusPainted(false);
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jPanel2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 50, 50));

        jButton12.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 0, 51));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton12.setText("6");
        jButton12.setFocusPainted(false);
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jPanel2.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 50, 50));

        jButton13.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton13.setForeground(new java.awt.Color(0, 0, 51));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton13.setText("5");
        jButton13.setFocusPainted(false);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jPanel2.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 50, 50));

        jButton14.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton14.setForeground(new java.awt.Color(0, 0, 51));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton14.setText("4");
        jButton14.setFocusPainted(false);
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jPanel2.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 50, 50));

        jButton15.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton15.setForeground(new java.awt.Color(0, 0, 51));
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton15.setText(".");
        jButton15.setFocusPainted(false);
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton15.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jPanel2.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 50, 50));

        jButton16.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton16.setForeground(new java.awt.Color(0, 0, 51));
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton16.setText("2");
        jButton16.setFocusPainted(false);
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton16.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jPanel2.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 50, 50));

        jButton17.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton17.setForeground(new java.awt.Color(0, 0, 51));
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton17.setText("3");
        jButton17.setFocusPainted(false);
        jButton17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton17.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jPanel2.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 50, 50));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 290, 50));

        jButton18.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton18.setForeground(new java.awt.Color(0, 0, 51));
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton18.setText("C");
        jButton18.setFocusPainted(false);
        jButton18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton18.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        jButton19.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton19.setForeground(new java.awt.Color(0, 0, 51));
        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton19.setText("1");
        jButton19.setFocusPainted(false);
        jButton19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton19.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jPanel2.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 50, 50));

        jButton20.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jButton20.setForeground(new java.awt.Color(0, 0, 51));
        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm).png"))); // NOI18N
        jButton20.setText("0");
        jButton20.setFocusPainted(false);
        jButton20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton20.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sin título (50 x 50 cm) (5 x 5 cm).png"))); // NOI18N
        jPanel2.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 50, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 290, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        System.out.println("Se presiono Borrar");
        textooperacion.setText("");
        textoresultado.setText("");
        
    }//GEN-LAST:event_jButton18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel textooperacion;
    private javax.swing.JLabel textooperacion1;
    private javax.swing.JLabel textoresultado;
    private javax.swing.JLabel textoresultado1;
    // End of variables declaration//GEN-END:variables
}
